### ISSUE TITLE
Outdated packages

### ISSUE THREAD

**Issue by nhamilakis** [arkark/latexmk-docker#10]
Hello, I pulled the `arkark/latexmk:full` image and then tried to install a package using `tlmgr` but got this issue : 

```
tlmgr: Local TeX Live (2020) is older than remote repository (2021).
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
See https://tug.org/texlive/upgrade.html for details.
```

Would it be possible to have an updated build version upstream ?

**Comment by arkark** [comment]
Thank you for your report. I'll update the build version, but please wait a while as I'm busy now.

btw, please write the commands you ran to reproduce the error.

**Comment by nhamilakis** [comment]
Thanks for the quick answer. 
I tried to install some fonts with `tlmgr install gfsdidot`.
I forked your repository and just had to change the date from 2020 to 2021 in the texlive urls.
Also i removed the ubuntu:eoan tag as that release of ubuntu is deprecated. 

If you like i could make a pull request.

**Comment by arkark** [comment]
Your forked repository looks good to me, and I welcome your PR.
